spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.139.21:1521:PROD2
        username: XYG_ALWEB
        password: XYG_ALWEB
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    redis:
      database: 10
      host: 192.168.88.31
#      password:
      port: 6379
      timeout: 0
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数
        
    dubbo:
        application.name: jebms-erp # 本服务的名称
        registry.address: zookeeper://192.168.99.100:2182 # ZooKeeper所在服务器的IP和端口号
        protocol.name: dubbo # RPC通信所采用的协议
        protocol.port: 20883 # 本服务对外暴露的端口号
        scan: com.jebms.erp.service.impl # 服务实现类所在的路径

security:
  jwt:
    secret: k09BQnaF
    tokenExpiration: 604800 #7Days 604800
    expiration: 86400 #1Day
