server:
    port: 8002
    ipAddress: 192.168.99.100

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-zuul

zuul:
    routes:
        producer.path: /jebms/erp/**
        producer.serviceId: jebms-erp

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${server.ipAddress}
        instance-id: ${server.ipAddress}:${server.port}
        hostname: ${server.ipAddress}
    client:
        serviceUrl.defaultZone: http://${server.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30
