server:
    port: 8002
    # 由于用了docker部署整个微服务，所以要配置docker宿主的ip地址！
    ipAddress: 192.168.0.48

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-zuul

zuul:
    sensitiveHeaders:  # 使用空来覆盖默认值
    host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
    addProxyHeaders: true
    routes:
        fnd:
            path: /jebms/fnd/**
            serviceId: jebms-fnd
            stripPrefix: false # 请求路径需要添加所匹配path
        erp:
            path: /jebms/erp/**
            serviceId: jebms-erp
            stripPrefix: false
        per:
            path: /jebms/per/**
            serviceId: jebms-per
            stripPrefix: false

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${server.ipAddress}
        instance-id: ${server.ipAddress}:${server.port}
        hostname: ${server.ipAddress}
    client:
        serviceUrl.defaultZone: http://${server.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30

ribbon:
    ReadTimeout: 60000  
    ConnectTimeout: 60000 

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000 
