server:
    port: 8002

spring:
    # 环境 dev|test|pro
    profiles:
        active: '@profileActive@'
    application:
        name: jebms-server-zuul

zuul:
    sensitiveHeaders:  # 使用空来覆盖默认值
    host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
    addProxyHeaders: true
    routes:
        fnd:
            path: /jebms/fnd/**
            serviceId: jebms-fnd
            stripPrefix: false # 请求路径需要添加所匹配path
        erp:
            path: /jebms/erp/**
            serviceId: jebms-erp
            stripPrefix: false
        per:
            path: /jebms/per/**
            serviceId: jebms-per
            stripPrefix: false

#禁用Eureka对Ribbon服务实例的维护实现。
ribbon.eureka.enabled: false
jebms-fnd.ribbon.listOfServers: ${eureka.ipAddress}:8080
jebms-erp.ribbon.listOfServers: ${eureka.ipAddress}:8081
jebms-per.ribbon.listOfServers: ${eureka.ipAddress}:8082

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${eureka.ipAddress}
        instance-id: ${eureka.ipAddress}:${server.port}
        hostname: ${eureka.ipAddress}
    client:
        serviceUrl.defaultZone: http://${eureka.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30

ribbon:
    ReadTimeout: 60000  
    ConnectTimeout: 60000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
hystrix.command.default.execution.timeout.enabled: false 

