server:
    port: 8002

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-zuul

zuul:
    routes:
        producer.path: /jebms/erp/**
        producer.serviceId: jebms-erp

eureka:
    instance:
        prefer-ip-address: true
        ip-address: 192.168.99.100
        instance-id: 192.168.99.100:${server.port}
        hostname: 192.168.99.100
    client:
        serviceUrl.defaultZone: http://192.168.99.100:8001/eureka/
        eureka-server-read-timeout-seconds: 30
