server:
    port: 8001

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        hostname: ${spring.cloud.client.ipAddress}
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl.defaultZone: http://192.168.99.100:8001/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
