server:
    port: 8080

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        hostname: ${spring.cloud.client.ipAddress}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url.defaultZone: http://${spring.cloud.client.ipAddress}:8080/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
