server:
    port: 8001
    ip-address: 192.168.99.100

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${server.ipAddress}
        instance-id: ${server.ipAddress}:${server.port}
        hostname: ${server.ipAddress}
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url.defaultZone: http://${server.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
