server:
    port: 8001

spring:
    # 环境 dev|test|pro
    profiles:
        active: '@profileActive@'
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${docker.host.ipAddress}
        instance-id: ${docker.host.ipAddress}:${server.port}
        hostname: ${docker.host.ipAddress}
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url.defaultZone: http://${docker.host.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 30000
