server:
    port: 8001

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
        ip-address: 192.168.99.100
        instance-id: 192.168.99.100:${server.port}
        hostname: 192.168.99.100
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url.defaultZone: http://192.168.99.100:8001/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
