server:
    port: 8001

spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-server-eureka

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url.defaultZone: http://localhost:8080/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
