# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8282
    context-path: /jebms/per

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: '@profileActive@'
    application:
        name: jebms-per
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${eureka.ipAddress}
        instance-id: ${eureka.ipAddress}:${server.port}
        hostname: ${eureka.ipAddress}
    client:
        service-url.defaultZone: http://${eureka.ipAddress}:8201/eureka/
        eureka-server-read-timeout-seconds: 30

# Mybatis配置
mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

mapper:
    #mappers:  - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

hystrix.command.default.execution.isolation.strategy: SEMAPHORE
hystrix.command.default.execution.timeout.enabled: false 
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000

