# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    context-path: /jebms

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-per
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        hostname: ${spring.cloud.client.ipAddress}
    client:
        serviceUrl.defaultZone: http://192.168.99.100:8001/eureka/

# Mybatis配置
mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

mapper:
    #mappers:  - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


