# 配置docker宿主的ip地址
docker.host.ipAddress: 192.168.0.48

spring:
    datasource:
        url: jdbc:mysql://192.168.88.31:3306/jebms_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: erp
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    redis:
      database: 10
      host: 192.168.88.31
#      password:
      port: 6379
      timeout: 0
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数

security:
  jwt:
    secret: k09BQnaF
    tokenExpiration: 604800 #7Days 604800
    expiration: 86400 #1Day

   