# 配置docker宿主的ip地址
docker.host.ipAddress: 192.168.0.48

spring:
    datasource:
        url: jdbc:mysql://192.168.68.1:3306/jebms_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: bowen
        password: bowen.890
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    redis:
      database: 10
      host: 192.168.68.1
#      password:
      port: 6379
      timeout: 0
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数
        
    ## Dubbo 服务消费者配置
    dubbo:
        application.name: jebms-fnd-consumer # 本服务的名称
        registry.address: zookeeper://192.168.99.100:2182 # ZooKeeper所在服务器的IP和端口号
        scan: com.jebms.fnd.service.impl # 引用服务的路径

security:
  jwt:
    secret: k09BQnaF
    tokenExpiration: 604800 #7Days 604800
    expiration: 86400 #1Day

global:
  edi:
     erpEdi: 