# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    context-path: /jebms
    ipAddress: 192.168.99.100

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    application:
        name: jebms-fnd
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false

eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${server.ipAddress}
        instance-id: ${server.ipAddress}:${server.port}
        hostname: ${server.ipAddress}
    client:
        service-url.defaultZone: http://${server.ipAddress}:8001/eureka/
        eureka-server-read-timeout-seconds: 30

# Mybatis配置
mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

mapper:
    #mappers:  - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

hystrix.command.default.execution.isolation.strategy: SEMAPHORE
#请求处理的超时时间  
ribbon.ReadTimeout: 120000  
#请求连接的超时时间  
ribbon.ConnectTimeout: 30000
